In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/project-2/Life Expectancy Data.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns

In [3]:
df=pd.read_csv("/kaggle/input/project-2/Life Expectancy Data.csv")
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [5]:
df.tail()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.0,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.0,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.0,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.0,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.0,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [6]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

It seems there are alot of missing Data let's begin by some Data Cleaning

In [7]:
df["Life expectancy "].fillna(df["Life expectancy "].mean(),inplace=True)
df[["Adult Mortality"].fillna(df["Adult Mortality"].mean(),inplace=True)
df[["Alcohol"].fillna(data["Alcohol"].mean(),inplace=True)
df[["Hepatitis B"].fillna(data["Hepatitis B"].mean(),inplace=True)
df[" BMI "].fillna(data[" BMI "].mean(),inplace=True)
df["Polio"].fillna(data["Polio"].mean(),inplace=True)
df["Total expenditure"].fillna(data["Total expenditure"].mean(),inplace=True)
df["Diphtheria "].fillna(data["Diphtheria "].mean(),inplace=True)
df["Population"].fillna(round(data["Population"].mean(),ndigits=2),inplace=True)
df["GDP"].fillna(data["GDP"].mean(),inplace=True)
df[" thinness  1-19 years"].fillna(data[" thinness  1-19 years"].mean(),inplace=True)
df[" thinness 5-9 years"].fillna(data[" thinness 5-9 years"].mean(),inplace=True)
df["Income composition of resources"].fillna(data["Income composition of resources"].mean(),inplace=True)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1420179550.py, line 2)

In [ ]:
df.duplicated().sum()

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.describe()

In [ ]:
df.fillna(0)

In [ ]:
df.nunique()

In [ ]:
print(df.dtypes)

In [ ]:
df.columns

In [ ]:
df['Country'].value_counts()

In [ ]:
df.shape

In [ ]:
df.isna()

In [ ]:
df.clip()

In [ ]:
df.sort_values('Year')

In [ ]:
df.dropna()

In [ ]:


df.drop('Schooling',axis= 1,inplace=False)

In [ ]:
plt.style.use('dark_background')
plt.figure(figsize=(8, 5))
sns.histplot(df["Life expectancy "], kde=False, bins=30,color="purple")
plt.title("Distribution of Life Expectancy")
plt.xlabel("Life Expectancy")
plt.tight_layout()
plt.show()

In [ ]:

plt.figure(figsize=(11,6))
df.groupby('Year')['Life expectancy '].mean().plot(kind='line', color='blue')
plt.title('Global Life Expectancy Over Time')
plt.xlabel('Year')
plt.ylabel('Life Expectancy')
plt.grid()
plt.show()

In [ ]:
plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='GDP', y='Life expectancy ', color = 'Green')
plt.title('Life Expectancy vs GDP per capita')
plt.xlabel('GDP per capita')
plt.ylabel('Life Expectancy')
plt.show

In [ ]:
plt.figure(figsize=(10,6))
sns.boxplot(data=df, x="Status", y="Schooling")
plt.title("Schooling by Country Status")
plt.xlabel("Status")
plt.ylabel("Schooling")
plt.show()

In [ ]:
top_10_countries = df.groupby('Country')['Life expectancy '].mean().sort_values(ascending=False).head(10)
top_10_countries.plot(kind='bar', color='orange')
plt.title('Top 10 Countries with Highest Life Expectancy')
plt.xlabel('Country')
plt.ylabel('Life Expectancy')
plt.xticks(rotation=45)
plt.show()